apiVersion: rabbitmq.mirantis.com/v1alpha1
kind: RabbitMQ
metadata:
  name: example-rabbitmq
spec:
  # Add fields here
  replicas: 3
  image: rabbitmq:3.7
  service_account: rabbitmq
  discovery_service: rabbitmq
